//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using AnjLab.FX.System;
using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("0.1.3828.0")]
[assembly: AssemblyFileVersion("0.1.3828.0")]
[assembly: AssemblyBuildDate("12/04/2017")]
[assembly: AssemblyCompany("AnjLab")]
[assembly: AssemblyProduct("AnjLab Sql Express Profiler")]


